version: "3.9"
services:
    biu:
        image: biu_flask:latest
        container_name: flask
        restart: always
        environment:
            MONGO_USERNAME: $MONGO_ROOT_USER
            MONGO_PASSWORD: $MONGO_ROOT_PASSWORD
        ports:
            - 3000:3000
        build:
            context: ./RestAPI
            dockerfile: Dockerfile
        depends_on:
            - mongo
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_BASICAUTH_USERNAME: $MONGOEXPRESS_LOGIN
            ME_CONFIG_BASICAUTH_PASSWORD: $MONGOEXPRESS_PASSWORD
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USER
            ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
        links:
            - mongo:mongodb
        depends_on:
        - mongo
    mongo:
        container_name: mongodb
        hostname: mongodb
        image: mongo:latest
        restart: always
        volumes:
            - ./mongod.conf:/etc/mongod.conf
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
        ports:
            - 27017:27017
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    mongoclient:
        image: mongoclient/mongoclient:latest
        container_name: mongoclient
        hostname: mongoclient
        environment: 
            MONGO_URL: $MONGO_URL
            MONGOCLIENT_DEFAULT_CONNECTION_URL: $MONGO_URL
            MONGOCLIENT_AUTH: "true"
            MONGOCLIENT_USERNAME: $MONGOEXPRESS_LOGIN
            MONGOCLIENT_PASSWORD: $MONGOEXPRESS_PASSWORD
        depends_on:
            - mongo
        links:
            - mongo:mongodb
        ports:
            - 3300:3000
